#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "SWGDefaultApi.h"
#import "JSONValueTransformer+ISO8601.h"
#import "SWGApi.h"
#import "SWGApiClient.h"
#import "SWGBasicAuthTokenProvider.h"
#import "SWGConfiguration.h"
#import "SWGDefaultConfiguration.h"
#import "SWGJSONRequestSerializer.h"
#import "SWGLogger.h"
#import "SWGObject.h"
#import "SWGQueryParamCollection.h"
#import "SWGResponseDeserializer.h"
#import "SWGSanitizer.h"
#import "SWGAccessToken.h"
#import "SWGAccount.h"
#import "SWGAccountsListItem.h"
#import "SWGActionType.h"
#import "SWGActivationPeriod.h"
#import "SWGActivationRangeType.h"
#import "SWGBattery.h"
#import "SWGButtonCategory.h"
#import "SWGButtonCreateRequest.h"
#import "SWGButtonGetDetails.h"
#import "SWGButtonPutDetails.h"
#import "SWGButtonsListItem.h"
#import "SWGButtonStoreCreateRequest.h"
#import "SWGChangeAccountRequest.h"
#import "SWGErrorResponse.h"
#import "SWGEvent.h"
#import "SWGEventType.h"
#import "SWGImage.h"
#import "SWGInitPreferences.h"
#import "SWGLatlng.h"
#import "SWGLocation.h"
#import "SWGLoginFacebookRequest.h"
#import "SWGLoginRequest.h"
#import "SWGMapDetails.h"
#import "SWGMapListItem.h"
#import "SWGMarker.h"
#import "SWGMobility.h"
#import "SWGNearbyResponse.h"
#import "SWGNearbySpotsListItem.h"
#import "SWGNotification.h"
#import "SWGPermissionType.h"
#import "SWGPlaceCreateRequest.h"
#import "SWGPlaceGetDetails.h"
#import "SWGPlacePutDetails.h"
#import "SWGPlacesListItem.h"
#import "SWGPlacesSearchRequest.h"
#import "SWGRadio.h"
#import "SWGRedirectInfo.h"
#import "SWGRegisterRequest.h"
#import "SWGSearchPreferences.h"
#import "SWGSearchRequest.h"
#import "SWGSearchResponse.h"
#import "SWGServerLastResponse.h"
#import "SWGSpotButtonCreateRequest.h"
#import "SWGSpotButtonResponse.h"
#import "SWGSpotCreateRequest.h"
#import "SWGSpotGetDetails.h"
#import "SWGSpotLayoutType.h"
#import "SWGSpotPutDetails.h"
#import "SWGSpotSearchResponse.h"
#import "SWGSpotsListItem.h"
#import "SWGSpotType.h"
#import "SWGTemplateType.h"
#import "SWGTileBounds.h"
#import "SWGTokens.h"
#import "SWGUser.h"
#import "SWGUserInfo.h"
#import "SWGUserPutDetails.h"
#import "SWGVisibilityType.h"

FOUNDATION_EXPORT double SwaggerClientVersionNumber;
FOUNDATION_EXPORT const unsigned char SwaggerClientVersionString[];

