#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGButtonCategory.h"
@protocol SWGButtonCategory;
@class SWGButtonCategory;



@protocol SWGButtonsListItem
@end

@interface SWGButtonsListItem : SWGObject

/* Button id 
 */
@property(nonatomic) NSString* _id;

@property(nonatomic) NSNumber* isActive;
/* The type of the button, like \"Pizza\" [optional]
 */
@property(nonatomic) NSString* type;
/* The name of the button, like \"Pizza Domino\" 
 */
@property(nonatomic) NSString* name;
/* The label of the button, like \"Get pizza Domino\" [optional]
 */
@property(nonatomic) NSString* label;
/* Button description [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) SWGButtonCategory* category;
/* Button color [optional]
 */
@property(nonatomic) NSString* color;
/* Button icon [optional]
 */
@property(nonatomic) NSString* icon;
/* Parent account button id [optional]
 */
@property(nonatomic) NSString* parent;

@end
