#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGButtonPutDetails
@end

@interface SWGButtonPutDetails : SWGObject

/* Button id 
 */
@property(nonatomic) NSString* _id;
/* The name of the button, like \"Pizza Domino\" [optional]
 */
@property(nonatomic) NSString* name;
/* The label of the button, like \"Get pizza Domino\" [optional]
 */
@property(nonatomic) NSString* label;

@property(nonatomic) NSNumber* isActive;
/* Button description [optional]
 */
@property(nonatomic) NSString* _description;
/* Button color [optional]
 */
@property(nonatomic) NSString* color;
/* Button icon [optional]
 */
@property(nonatomic) NSString* icon;
/* Button configuration [optional]
 */
@property(nonatomic) NSString* configuration;

@end
