#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGButtonCategory.h"
@protocol SWGButtonCategory;
@class SWGButtonCategory;



@protocol SWGButtonStoreCreateRequest
@end

@interface SWGButtonStoreCreateRequest : SWGObject

/* The type of the button, like \"Pizza\" 
 */
@property(nonatomic) NSString* type;
/* The name of the button, like \"Pizza Domino\" [optional]
 */
@property(nonatomic) NSString* name;
/* The label of the button, like \"Get pizza Domino\" [optional]
 */
@property(nonatomic) NSString* label;
/* Button description [optional]
 */
@property(nonatomic) NSString* _description;
/* Button color [optional]
 */
@property(nonatomic) NSString* color;
/* Button icon [optional]
 */
@property(nonatomic) NSString* icon;

@property(nonatomic) SWGButtonCategory* category;
/* URL to the button's web application 
 */
@property(nonatomic) NSString* indexUrl;
/* URL to button's administation web application [optional]
 */
@property(nonatomic) NSString* adminUrl;
/* URL to button's API definition [optional]
 */
@property(nonatomic) NSString* swaggerUrl;
/* button author [optional]
 */
@property(nonatomic) NSString* author;
/* button application version [optional]
 */
@property(nonatomic) NSString* version;
/* Button's long description [optional]
 */
@property(nonatomic) NSString* longDescription;
/* Button's overview [optional]
 */
@property(nonatomic) NSString* overview;

@end
