#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGBeaconTrigger
@end

@interface SWGBeaconTrigger : SWGObject

/* Beacon type 
 */
@property(nonatomic) NSString* type;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSNumber* major;

@property(nonatomic) NSNumber* minor;

@property(nonatomic) NSNumber* txPower;

@property(nonatomic) NSNumber* distance;

@end
