#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGButtonCategory.h"
@protocol SWGButtonCategory;
@class SWGButtonCategory;



@protocol SWGButtonGetDetails
@end

@interface SWGButtonGetDetails : SWGObject

/* Button id 
 */
@property(nonatomic) NSString* _id;
/* The type of the button, like \"Pizza\" 
 */
@property(nonatomic) NSString* type;
/* The name of the button, like \"Pizza Domino\" [optional]
 */
@property(nonatomic) NSString* name;
/* The label of the button, like \"Get pizza Domino\" [optional]
 */
@property(nonatomic) NSString* label;

@property(nonatomic) NSNumber* isActive;
/* ID to an account button [optional]
 */
@property(nonatomic) NSString* button;
/* ID to a parent button [optional]
 */
@property(nonatomic) NSString* parent;
/* ID to a store button [optional]
 */
@property(nonatomic) NSString* storeButton;
/* Button description [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) SWGButtonCategory* category;
/* Button color [optional]
 */
@property(nonatomic) NSString* color;
/* Button icon [optional]
 */
@property(nonatomic) NSString* icon;
/* URL to the button's web application 
 */
@property(nonatomic) NSString* indexUrl;
/* URL to button's administation web application [optional]
 */
@property(nonatomic) NSString* adminUrl;
/* URL to button's API definition [optional]
 */
@property(nonatomic) NSString* swaggerUrl;
/* Button configuration [optional]
 */
@property(nonatomic) NSString* configuration;
/* button author [optional]
 */
@property(nonatomic) NSString* author;
/* button application version [optional]
 */
@property(nonatomic) NSString* version;
/* Button's long description [optional]
 */
@property(nonatomic) NSString* longDescription;
/* Button's overview [optional]
 */
@property(nonatomic) NSString* overview;

@end
