#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGActionType.h"
#import "SWGEventType.h"
#import "SWGNotification.h"
@protocol SWGActionType;
@class SWGActionType;
@protocol SWGEventType;
@class SWGEventType;
@protocol SWGNotification;
@class SWGNotification;



@protocol SWGEvent
@end

@interface SWGEvent : SWGObject


@property(nonatomic) SWGEventType* type;
/* Spot or Place id depending on the event type [optional]
 */
@property(nonatomic) NSString* objectId;

@property(nonatomic) SWGActionType* actionType;

@property(nonatomic) SWGNotification* notification;

@end
