#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGeofenceTrigger
@end

@interface SWGGeofenceTrigger : SWGObject

/* Trigger type 
 */
@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* longitude;

@property(nonatomic) NSNumber* latitude;

@property(nonatomic) NSNumber* radius;

@property(nonatomic) NSArray<NSString*>* notifyOn;
/* Used to identify fiered trigger [optional]
 */
@property(nonatomic) NSString* geofenceId;

@end
