#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInitPreferences
@end

@interface SWGInitPreferences : SWGObject


@property(nonatomic) NSString* aRRAYMINPOWERDETECT;

@property(nonatomic) NSString* gPSMAXTIMEDETECT;

@property(nonatomic) NSString* gPSSEARCHRADIUS;

@property(nonatomic) NSString* rADIOARRAYDISTANCETOLERANCE;

@property(nonatomic) NSString* pLACEMINPOWERCREATE;

@property(nonatomic) NSString* pLACEMINPOWERDETECT;

@property(nonatomic) NSString* aRRAYMINPOWERCREATE;

@property(nonatomic) NSString* mINTIMELOCATION;

@property(nonatomic) NSString* mINTIMERADIO;

@property(nonatomic) NSString* mOTIONSENSITIVITY;

@property(nonatomic) NSString* mAPSHOWSPOTSATZOOM;

@property(nonatomic) NSString* sENSORSSTOPTIME;

@property(nonatomic) NSString* mOBILITYCHANGETIME;
/* Response from search which sets up the minimum speed (in meters per sec) that halts motion detection. [optional]
 */
@property(nonatomic) NSNumber* lOCOMOTIONMINSPEED;

@end
