#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGLocation
@end

@interface SWGLocation : SWGObject


@property(nonatomic) NSNumber* latitude;

@property(nonatomic) NSNumber* longitude;

@property(nonatomic) NSNumber* accuracy;

@property(nonatomic) NSNumber* time;

@property(nonatomic) NSNumber* speed;

@property(nonatomic) NSNumber* radius;

@property(nonatomic) NSString* source;

@property(nonatomic) NSString* availableSources;

@property(nonatomic) NSNumber* sensorUpTime;

@end
