#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGMobility
@end

@interface SWGMobility : SWGObject

/* Accelerometer based estimation if the device is moving or stationary [optional]
 */
@property(nonatomic) NSNumber* isMoving;
/* How long the device has been in moving or stationary state [optional]
 */
@property(nonatomic) NSNumber* time;

@end
