#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLatlng.h"
#import "SWGTileBounds.h"
@protocol SWGLatlng;
@class SWGLatlng;
@protocol SWGTileBounds;
@class SWGTileBounds;



@protocol SWGMapDetails
@end

@interface SWGMapDetails : SWGObject

/* Place id [optional]
 */
@property(nonatomic) NSString* _id;
/* Map name [optional]
 */
@property(nonatomic) NSString* name;

@property(nonatomic) NSString* placeId;
/* An array of top/left and bottom/down corners [optional]
 */
@property(nonatomic) NSArray<SWGLatlng>* bounds;

@property(nonatomic) SWGLatlng* center;

@property(nonatomic) NSString* floor;
/* An array of time bounds for each zoom level [optional]
 */
@property(nonatomic) NSArray<SWGTileBounds>* tilesBounds;

@property(nonatomic) NSString* tilesUrl;

@end
