#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGMapListItem
@end

@interface SWGMapListItem : SWGObject

/* Map id [optional]
 */
@property(nonatomic) NSString* _id;
/* Map name [optional]
 */
@property(nonatomic) NSString* name;

@property(nonatomic) NSString* floor;

@property(nonatomic) NSString* placeId;

@end
