#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGMarker
@end

@interface SWGMarker : SWGObject


@property(nonatomic) NSString* type;
/* Depends on marker type, e.g. CODABAR type of BARCODE type or AZTEC type of QRCODE type, EDDYSTONE_UID, EDDYSTONE_URL, ALTBEACON, IBEACON [optional]
 */
@property(nonatomic) NSString* subtype;
/* UNIQUE! The code behind a visual marker type (QRCODE, BARCODE, ARCODE), SSID of a WiFi access point or the MAC of a Bluetooth device. 
 */
@property(nonatomic) NSString* identifier;
/* UNIQUE! The MAC address of the WiFi access point or a BLE device [optional]
 */
@property(nonatomic) NSString* mac;

@property(nonatomic) NSNumber* powerLimit;

@end
