#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGNearbySpotsListItem.h"
#import "SWGPlacesListItem.h"
@protocol SWGNearbySpotsListItem;
@class SWGNearbySpotsListItem;
@protocol SWGPlacesListItem;
@class SWGPlacesListItem;



@protocol SWGNearbyResponse
@end

@interface SWGNearbyResponse : SWGObject

/* An array of nearby spots [optional]
 */
@property(nonatomic) NSArray<SWGNearbySpotsListItem>* spots;
/* An array of nearby places [optional]
 */
@property(nonatomic) NSArray<SWGPlacesListItem>* places;

@end
