#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLocation.h"
#import "SWGRadio.h"
#import "SWGSpotButtonResponse.h"
#import "SWGSpotLayoutType.h"
#import "SWGSpotType.h"
#import "SWGVisibilityType.h"
@protocol SWGLocation;
@class SWGLocation;
@protocol SWGRadio;
@class SWGRadio;
@protocol SWGSpotButtonResponse;
@class SWGSpotButtonResponse;
@protocol SWGSpotLayoutType;
@class SWGSpotLayoutType;
@protocol SWGSpotType;
@class SWGSpotType;
@protocol SWGVisibilityType;
@class SWGVisibilityType;



@protocol SWGNearbySpotsListItem
@end

@interface SWGNearbySpotsListItem : SWGObject

/* Spot id 
 */
@property(nonatomic) NSString* _id;
/* The name of the spot 
 */
@property(nonatomic) NSString* name;

@property(nonatomic) SWGSpotType* type;
/* The description of the spot [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) SWGVisibilityType* visibilityType;

@property(nonatomic) NSArray<SWGRadio>* radioArray;

@property(nonatomic) SWGLocation* location;

@property(nonatomic) NSNumber* isActive;
/* Base64 encoded jpeg compressed thumbnail of the spot image [optional]
 */
@property(nonatomic) NSString* thumbnail;

@property(nonatomic) NSString* floor;

@property(nonatomic) SWGSpotLayoutType* layoutType;
/* List of buttons attached to the spot [optional]
 */
@property(nonatomic) NSArray<SWGSpotButtonResponse>* buttons;
/* true if the spot is liked [optional]
 */
@property(nonatomic) NSNumber* isLiked;
/* true if the spot is banned [optional]
 */
@property(nonatomic) NSNumber* isBanned;
/* true if the spot is pinned [optional]
 */
@property(nonatomic) NSNumber* isPinned;

@end
