#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLocation.h"
@protocol SWGLocation;
@class SWGLocation;



@protocol SWGPlacesListItem
@end

@interface SWGPlacesListItem : SWGObject

/* Place id [optional]
 */
@property(nonatomic) NSString* _id;
/* Place name [optional]
 */
@property(nonatomic) NSString* name;
/* Number of maps attached to this place [optional]
 */
@property(nonatomic) NSNumber* mapsCount;
/* Place image thumbnail [optional]
 */
@property(nonatomic) NSString* thumbnail;
/* true if the place is active [optional]
 */
@property(nonatomic) NSNumber* isActive;

@property(nonatomic) NSNumber* spotsCount;

@property(nonatomic) NSNumber* visitorsCount;

@property(nonatomic) SWGLocation* location;

@property(nonatomic) NSString* floor;
/* True if the client must show spots only from that place, false for places like Malls [optional]
 */
@property(nonatomic) NSNumber* isExplicit;

@end
