#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLocation.h"
#import "SWGMapListItem.h"
#import "SWGMarker.h"
#import "SWGRadio.h"
@protocol SWGLocation;
@class SWGLocation;
@protocol SWGMapListItem;
@class SWGMapListItem;
@protocol SWGMarker;
@class SWGMarker;
@protocol SWGRadio;
@class SWGRadio;



@protocol SWGPlaceGetDetails
@end

@interface SWGPlaceGetDetails : SWGObject

/* Place id 
 */
@property(nonatomic) NSString* _id;
/* Place name 
 */
@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* isActive;

@property(nonatomic) SWGMarker* marker;
/* Place detection by current position. Mutually exclusive with marker. [optional]
 */
@property(nonatomic) NSArray<SWGRadio>* radioArray;

@property(nonatomic) NSString* radioArrayTime;

@property(nonatomic) SWGLocation* location;
/* Google's place id [optional]
 */
@property(nonatomic) NSString* googlePlaceId;

@property(nonatomic) NSArray<SWGMapListItem>* maps;

@property(nonatomic) NSString* webSiteUrl;
/* Place image url [optional]
 */
@property(nonatomic) NSString* image;
/* Place thumbnail url [optional]
 */
@property(nonatomic) NSString* thumbnail;

@property(nonatomic) NSNumber* spotsCount;

@property(nonatomic) NSNumber* visitorsCount;

@property(nonatomic) NSString* floor;

@property(nonatomic) NSNumber* isVerified;
/* True if the client must show spots only from that place, false for places like Malls [optional]
 */
@property(nonatomic) NSNumber* isExplicit;

@end
