#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLocation.h"
#import "SWGRadio.h"
@protocol SWGLocation;
@class SWGLocation;
@protocol SWGRadio;
@class SWGRadio;



@protocol SWGPlacesSearchRequest
@end

@interface SWGPlacesSearchRequest : SWGObject


@property(nonatomic) SWGLocation* location;

@property(nonatomic) NSArray<SWGRadio>* radioArray;

@end
