#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGRadio
@end

@interface SWGRadio : SWGObject


@property(nonatomic) NSString* type;
/* SSID in case of WiFi or Device Name in case of BLE beacon 
 */
@property(nonatomic) NSString* identifier;
/* Radio signal strength in dBm [optional]
 */
@property(nonatomic) NSNumber* power;
/* Radio channel width [optional]
 */
@property(nonatomic) NSNumber* channel;
/* UNIQUE! The MAC address of the WiFi access point or a BLE device [optional]
 */
@property(nonatomic) NSString* mac;
/* true if the wifi is currently connected to the device [optional]
 */
@property(nonatomic) NSNumber* isConnected;

@end
