#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGActivationPeriod.h"
#import "SWGActivationRangeType.h"
#import "SWGButtonsListItem.h"
#import "SWGLocation.h"
#import "SWGMarker.h"
#import "SWGPlaceGetDetails.h"
#import "SWGRadio.h"
#import "SWGSpotLayoutType.h"
#import "SWGSpotType.h"
#import "SWGTemplateType.h"
#import "SWGVisibilityType.h"
@protocol SWGActivationPeriod;
@class SWGActivationPeriod;
@protocol SWGActivationRangeType;
@class SWGActivationRangeType;
@protocol SWGButtonsListItem;
@class SWGButtonsListItem;
@protocol SWGLocation;
@class SWGLocation;
@protocol SWGMarker;
@class SWGMarker;
@protocol SWGPlaceGetDetails;
@class SWGPlaceGetDetails;
@protocol SWGRadio;
@class SWGRadio;
@protocol SWGSpotLayoutType;
@class SWGSpotLayoutType;
@protocol SWGSpotType;
@class SWGSpotType;
@protocol SWGTemplateType;
@class SWGTemplateType;
@protocol SWGVisibilityType;
@class SWGVisibilityType;



@protocol SWGSpotGetDetails
@end

@interface SWGSpotGetDetails : SWGObject

/* Spot's id 
 */
@property(nonatomic) NSString* _id;
/* Spot's name 
 */
@property(nonatomic) NSString* name;

@property(nonatomic) SWGSpotType* type;
/* Spot's description [optional]
 */
@property(nonatomic) NSString* _description;
/* true if the spot is active 
 */
@property(nonatomic) NSNumber* isActive;

@property(nonatomic) SWGTemplateType* templateType;
/* Spot image url [optional]
 */
@property(nonatomic) NSString* image;
/* Base64 encoded jpeg image [optional]
 */
@property(nonatomic) NSString* thumbnail;

@property(nonatomic) SWGMarker* marker;

@property(nonatomic) SWGActivationRangeType* activationRange;

@property(nonatomic) SWGActivationPeriod* activationPeriod;

@property(nonatomic) SWGVisibilityType* visibilityType;

@property(nonatomic) SWGSpotLayoutType* layoutType;

@property(nonatomic) NSArray<SWGRadio>* radioArray;

@property(nonatomic) NSString* radioArrayTime;
/* An array of places where the spot will be active [optional]
 */
@property(nonatomic) NSArray<SWGPlaceGetDetails>* places;

@property(nonatomic) SWGLocation* location;
/* An array of countries the spot will be active [optional]
 */
@property(nonatomic) NSArray<NSString*>* countries;
/* An array of buttons attached to the spot [optional]
 */
@property(nonatomic) NSArray<SWGButtonsListItem>* buttons;

@property(nonatomic) NSString* floor;
/* true if the spot is liked [optional]
 */
@property(nonatomic) NSNumber* isLiked;
/* true if the spot is banned [optional]
 */
@property(nonatomic) NSNumber* isBanned;
/* true if the spot is pinned [optional]
 */
@property(nonatomic) NSNumber* isPinned;

@end
