#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLocation.h"
#import "SWGMarker.h"
#import "SWGSpotButtonResponse.h"
#import "SWGSpotLayoutType.h"
#import "SWGSpotType.h"
@protocol SWGLocation;
@class SWGLocation;
@protocol SWGMarker;
@class SWGMarker;
@protocol SWGSpotButtonResponse;
@class SWGSpotButtonResponse;
@protocol SWGSpotLayoutType;
@class SWGSpotLayoutType;
@protocol SWGSpotType;
@class SWGSpotType;



@protocol SWGSpotSearchResponse
@end

@interface SWGSpotSearchResponse : SWGObject

/* Spot id 
 */
@property(nonatomic) NSString* _id;
/* The name of the spot 
 */
@property(nonatomic) NSString* name;
/* The description of the spot [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) SWGMarker* marker;
/* Thumbnail of the spot image [optional]
 */
@property(nonatomic) NSString* thumbnail;
/* List of buttons attached to the spot [optional]
 */
@property(nonatomic) NSArray<SWGSpotButtonResponse>* buttons;

@property(nonatomic) SWGSpotLayoutType* layoutType;

@property(nonatomic) NSString* floor;

@property(nonatomic) SWGSpotType* type;

@property(nonatomic) SWGLocation* location;
/* true if the spot is liked [optional]
 */
@property(nonatomic) NSNumber* isLiked;
/* true if the spot is banned [optional]
 */
@property(nonatomic) NSNumber* isBanned;
/* true if the spot is pinned [optional]
 */
@property(nonatomic) NSNumber* isPinned;

@end
