#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGSearchPreferences
@end

@interface SWGSearchPreferences : SWGObject

/* Response from search which sets up the interval for the next searches [optional]
 */
@property(nonatomic) NSString* hEARTBEATINTERVAL;
/* Response from search which sets up the location updates interval [optional]
 */
@property(nonatomic) NSString* lOCATIONINTERVAL;
/* Response from search which sets up the radio updates interval [optional]
 */
@property(nonatomic) NSString* rADIOINTERVAL;
/* Response from search which sets up a geofence radius [optional]
 */
@property(nonatomic) NSString* eMPTYGEOFENCERADIUS;
/* iOS HB mapping, related to CLLocationAccuracy [optional]
 */
@property(nonatomic) NSNumber* iOSLOCATIONACCURACY;
/* iOS HB mapping [optional]
 */
@property(nonatomic) NSString* iOSTIMERMETHOD;

@end
