#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLocation.h"
#import "SWGSpotType.h"
#import "SWGTemplateType.h"
@protocol SWGLocation;
@class SWGLocation;
@protocol SWGSpotType;
@class SWGSpotType;
@protocol SWGTemplateType;
@class SWGTemplateType;



@protocol SWGSpotsListItem
@end

@interface SWGSpotsListItem : SWGObject

/* Spot id 
 */
@property(nonatomic) NSString* _id;
/* The name of the spot 
 */
@property(nonatomic) NSString* name;

@property(nonatomic) SWGSpotType* type;
/* The description of the spot [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* isActive;

@property(nonatomic) SWGTemplateType* templateType;
/* Base64 encoded jpeg compressed thumbnail of the spot image [optional]
 */
@property(nonatomic) NSString* thumbnail;

@property(nonatomic) NSString* floor;

@property(nonatomic) SWGLocation* location;

@end
