#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGTokens
@end

@interface SWGTokens : SWGObject

/* access token, on expire refresh with the permanent token via auth/token-refresh [optional]
 */
@property(nonatomic) NSString* token;
/* permanent token [optional]
 */
@property(nonatomic) NSString* deviceToken;

@end
