#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGTileBounds
@end

@interface SWGTileBounds : SWGObject


@property(nonatomic) NSNumber* zoom;

@property(nonatomic) NSNumber* minX;

@property(nonatomic) NSNumber* minY;

@property(nonatomic) NSNumber* maxX;

@property(nonatomic) NSNumber* maxY;

@end
