#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* OnSpota API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAccount.h"
#import "SWGPermissionType.h"
#import "SWGUser.h"
@protocol SWGAccount;
@class SWGAccount;
@protocol SWGPermissionType;
@class SWGPermissionType;
@protocol SWGUser;
@class SWGUser;



@protocol SWGUserInfo
@end

@interface SWGUserInfo : SWGObject


@property(nonatomic) SWGUser* user;

@property(nonatomic) SWGAccount* account;
/* An array of user permissions [optional]
 */
@property(nonatomic) NSArray<SWGPermissionType>* permissions;

@end
